Modify .github/workflows/php-lint.yml

diff --git a/.github/workflows/php-lint.yml b/.github/workflows/php-lint.yml
--- a/.github/workflows/php-lint.yml
+++ b/.github/workflows/php-lint.yml
@@ -1,10 +1,6 @@
 name: PHP Lint
 
 on: [push, pull_request]
-#  push:
-#    branches: [ "master" ]
-#  pull_request:
-#    branches: [ "master" ]
 
 permissions:
   contents: read
@@ -34,8 +30,28 @@ jobs:
         with:
           php-version: "8.2"
 
-      - name: Install dependencies
+      - name: Install Composer dependencies
         run: composer install --prefer-dist --no-progress
+
+#      - name: Run PHP-CS-Fixer
+#        run: ./vendor/bin/php-cs-fixer fix --dry-run --config=.php-cs-fixer.dist.php -v --show-progress=dots --stop-on-violation --using-cache=no
+#
+#      - name: Check PHP-CS-Fixer exit code
+#        run: |
+#          if [ "${?}" -ne 0 ]; then
+#            echo "PHP-CS-Fixer complete with exit code not 0: ${?}";
+#            exit 1
+#          fi
+
+#      - name: Run PHPUnit tests
+#        run: ./vendor/bin/phpunit
+
+  php-cs-fixer:
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v3
 
       - name: Run PHP-CS-Fixer
         run: ./vendor/bin/php-cs-fixer fix --dry-run --config=.php-cs-fixer.dist.php -v --show-progress=dots --stop-on-violation --using-cache=no
@@ -46,6 +62,13 @@ jobs:
             echo "PHP-CS-Fixer complete with exit code not 0: ${?}";
             exit 1
           fi
+
+  phpunit:
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v3
 
       - name: Run PHPUnit tests
         run: ./vendor/bin/phpunit
